set(PWD "${CMAKE_CURRENT_LIST_DIR}")
include("${PWD}/Flags/Flags.cmake")
include("${PWD}/GLFW/glfw.cmake")
include("${PWD}/std/std.cmake")
include("${PWD}/Vulkan/vulkan.cmake")
include("${PWD}/Win/win.cmake")
include("${PWD}/Shaders/shaders.cmake")
include("${PWD}/vkCube/vkCube.cmake")
include("${PWD}/GLM/glm.cmake")