set(APP_GROUND_SHADER_DIR "${CMAKE_CURRENT_LIST_DIR}")

target_sources(
	${PROJECT_NAME} PUBLIC
	FILE_SET CXX_MODULES 
	BASE_DIRS ${APP_GROUND_SHADER_DIR}
	FILES
		"${APP_GROUND_SHADER_DIR}/ground_shader.cppm"
)